---
title: "2/18 Maps"
author: "Lainey Newman"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidycensus)
library(tidyverse)
library(dplyr)

census_api_key("9f9584127dd506cdaf80bdb78927e9c01c12f2b8", overwrite = TRUE)
readRenviron("~/.Renviron")


```

```{r, include = FALSE}

rural <- get_decennial(geography = "state",
                       variables = c("P001001", "P002005"),
                       year = 2010,
                       output = "wide")

racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")

harris <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "TX",
                  county = "Harris County",
                  geometry = TRUE,
                  summary_var = "B02001_001") 

harris %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot() +
  facet_wrap(~ variable) +
  geom_sf(aes(fill = Percent, color = Percent)) +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of Harris County, Texas",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()


allegheny <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "PA",
                  county = "Allegheny County",
                  geometry = TRUE,
                  summary_var = "B02001_001") 

```

```{r, echo = FALSE}

allegheny %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot() +
  facet_wrap(~ variable) +
  geom_sf(aes(fill = Percent, color = Percent)) +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of Allegheny County, Pennsylvania",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()
 


```



